### ISSUE TITLE
Nav bar design issue with drop down menus

### ISSUE THREAD

**Issue by Brandon1419** [chrisindfw/ifdlva#33]
https://ifdlva.com/admin/pirep.php

https://ifdlva.com/gallery.php

Drop down menus in navigation bar has blue text which blends in with background. Let me know if you need more info

**Comment by chrisindfw** [comment]
Will redesign the CSS for it.

**Comment by Brandon1419** [comment]
This is the error in the Console 

TypeError: $('ul.dropdown').superfish is not a function. (In '$('ul.dropdown').superfish({
		autoArrows: true,
		animation: {height:'show'}
	})', '$('ul.dropdown').superfish' is undefined)

**Comment by Brandon1419** [comment]
Issue is back only on Gallery page
