### ISSUE TITLE
Import Users

### ISSUE THREAD

**Issue by Brandon1419** [chrisindfw/ifdlva#38]
[tbl_users-2.xlsx](https://github.com/chrisindfw/ifdlva/files/2432071/tbl_users-2.xlsx)

**Comment by Brandon1419** [comment]
BETA TESTERS

[tbl_users.xlsx](https://github.com/chrisindfw/ifdlva/files/2435762/tbl_users.xlsx)

**Comment by chrisindfw** [comment]
Beta users are done.

**Comment by Brandon1419** [comment]
Done!
