### ISSUE TITLE
Deleting Pirep stats are not updated

### ISSUE THREAD

**Issue by chrisindfw** [chrisindfw/ifdlva#4]

**Comment by chrisindfw** [comment]
Only happens when deleting an approved one.

**Comment by Brandon1419** [comment]
Still having an issue here... Stats don't delete when PIREP gets deleted

**Comment by chrisindfw** [comment]
Ready for testing

**Comment by Brandon1419** [comment]
Will send to the alpha testers.

**Comment by Brandon1419** [comment]
Looking good! Fixed!
